#### ---------------------------------------------
#### ---- Web application images compose file ----:
#### ---------------------------------------------

version: '3'
services:
  # Set up image for web service.
  web:
    build: web/
    ports:
      - "8080:5000"
    depends_on:
      - mongo
    # Requires secret.py file in application directory
    volumes:
      - ./web:/app/web
      - ./secrets/secret.py:/app/web/secret.py
    environment:
      FLASK_ENV: development

  # Set up database image
  mongo:
    image: mongo:latest
    # Requires file with secret environment variables
    env_file:
      - ./secrets/db.env
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: on-failure

  # Set up mongo seeder image --
  # populates database with production data
  # as well as user login/password data
  mongo_seed:
    build:
      context: mongo_seed/
    # Requires file with secret environment variables
    env_file:
      - ./secrets/db.env
    links:
      - mongo
    restart: on-failure

  # Set up database web interface image
  mongo_web:
    image: mongo-express
    # Requires file with secret environment variables
    env_file:
      - ./secrets/db_web.env
    links:
      - mongo
    ports:
      - "19981:8081"
    restart: on-failure

# Set up volume for mongodb data
volumes:
  mongodb_data:
    driver: local
