version: '3.7'
services:
  # redis:
  #   image: "redis:alpine"

  web:
    build: web/
    ports:
      - "8080:5000"
    depends_on:
      - mongo
    volumes:
      - ./web:/app/web
      - ./secrets/secret.py:/app/web/secret.py
    environment:
      FLASK_ENV: development

  mongo:
    image: mongo:latest
    restart: always
    env_file:
      - secrets/db.env
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  mongo-seed:
    build:
      context: ./mongo-seed
    env_file:
      - secrets/db.env
    depends_on:
      - mongo
    restart: on-failure
    links:
      - mongo

  mongo_web:
    image: mongo-express
    ports:
      - "19981:8081"
    restart: on-failure
    env_file:
      - secrets/db_web.env
    links:
      - mongo
    depends_on:
      - mongo


volumes:
  mongodb_data:
    driver: local


# secrets:
#   mongodb_root_username:
#     file: ./secrets/.mongodb_root_username
#   mongodb_root_password:
#     file: ./secrets/.mongodb_root_password
